package servent.message;

public enum MessageType {
	PING, PONG, POISON, TRANSACTION,
	NAIVE_ASK_AMOUNT, NAIVE_TELL_AMOUNT,
	AB_TOKEN, AB_TELL,
	AV_TOKEN, AV_DONE, AV_TERMINATE,
	CL_MARKER, CL_TELL,
	LY_MARKER, LY_TELL
}
